version: 2


# Parallel build? NO... )

jobs:
  build:
    machine:
      docker_layer_caching: true
    steps:
      - checkout

      # PHP 7.4
      - run:
          name: PHP 7.4 application Docker image
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            make VERSION=7.4-latest PHP=74 alpine fix_circleci_bug image test push

      # PHP 7.3 LATEST STABLE
      - run:
          name: PHP 7.3 application Docker image
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            make VERSION=7.3-latest PHP=73 alpine fix_circleci_bug image test push
            docker tag $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:7.3-latest $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:latest
            docker push $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:latest

      # PHP 7.2
      - run:
          name: PHP 7.2 application Docker image
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            make VERSION=7.2-latest PHP=72 alpine fix_circleci_bug image test push

      # PHP 7.1
      - run:
          name: PHP 7.1 application Docker image
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            make VERSION=7.1-latest PHP=71 alpine fix_circleci_bug image test push

workflows:
  version: 2
  build:
    triggers:
      - schedule:
          cron: "0 0 * * 0" # Every week
          filters:
            branches:
              only:
                - master
    jobs:
      - build
